version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: adminhookapedia
      POSTGRES_PASSWORD: locKPassWord031
      POSTGRES_DB: dbhookapedia
    ports:
      - '5432:5432'
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  # Application
  backend:
    build: .
    container_name: hookapedia-backend
    ports:
      - '3001:3001'
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=adminhookapedia
      - DB_PASSWORD=locKPassWord031
      - DB_DATABASE=dbhookapedia
    command: npm run start:prod

# Redis (если понадобится для кэширования)
redis:
  image: redis:7-alpine
  container_name: hookapedia-redis
  restart: unless-stopped
  ports:
    - '6379:6379'
  volumes:
    - redis_data:/data
  networks:
    - hookapedia-network
  healthcheck:
    test: ['CMD', 'redis-cli', 'ping']
    interval: 10s
    timeout: 3s
    retries: 3

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  hookapedia-network:
    driver: bridge
