version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: hookapedia-postgres-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: hookapedia_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    networks:
      - hookapedia-dev-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Development Application with hot reload
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: hookapedia-backend-dev
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 3001
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: hookapedia_dev
    ports:
      - "3001:3001"
      - "9229:9229"  # Debug port
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - hookapedia-dev-network
    volumes:
      - .:/app
      - /app/node_modules
      - ./logs:/app/logs
    command: npm run start:debug

  # Redis for development
  redis:
    image: redis:7-alpine
    container_name: hookapedia-redis-dev
    restart: unless-stopped
    ports:
      - "6380:6379"
    volumes:
      - redis_dev_data:/data
    networks:
      - hookapedia-dev-network

volumes:
  postgres_dev_data:
    driver: local
  redis_dev_data:
    driver: local

networks:
  hookapedia-dev-network:
    driver: bridge
